Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  
  config.vm.provider :virtualbox do |v|
    v.memory = 1512
    v.cpus = 2
  end

  boxes = [
    {
      name: "backup",
      ip: "192.168.11.160",
      playbook: "playbooks/backup.yaml",
    },
    {
      name: "client",
      ip: "192.168.11.150", 
      playbook: "playbooks/client.yaml",
    },
  ]

  boxes.each do |opts|
    config.vm.define opts[:name] do |machine|
      machine.vm.hostname = opts[:name]
      machine.vm.network "private_network", ip: opts[:ip]
      machine.vm.provision :ansible do |ansible|
        ansible.playbook = opts[:playbook]
      end
    end
  end
end
