---
- hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - nginx
          - python3
          - python3-pip
          - python3-venv
          - gunicorn
          - nodejs
          - npm
          - php-fpm
          - php-cli
        state: present

    - name: Copy project
      copy:
        src: project/
        dest: /opt/webapps/

    - name: Setup Django
      shell: |
        cd /opt/webapps/python
        python3 -m venv venv
        . venv/bin/activate
        pip install django gunicorn
        nohup gunicorn --bind 127.0.0.1:8001 mysite.wsgi:application > /var/log/django.log 2>&1 &
      args:
        creates: /opt/webapps/python/venv/

    - name: Setup Node.js
      shell: |
        cd /opt/webapps/node
        npm init -y
        nohup node test.js > /var/log/nodejs.log 2>&1 &
      args:
        creates: /opt/webapps/node/package.json

    - name: Create PHP app
      copy:
        dest: /opt/webapps/php/index.php
        content: |
          <!DOCTYPE html>
          <html>
          <body>
              <h1>PHP App</h1>
              <p>Port: 8083</p>
          </body>
          </html>

    - name: Configure Nginx
      copy:
        src: project/nginx-conf/nginx.conf
        dest: /etc/nginx/sites-available/webapps

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/webapps
        dest: /etc/nginx/sites-enabled/webapps
        state: link

    - name: Remove default site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Start PHP-FPM
      systemd:
        name: php8.1-fpm
        state: started
        enabled: yes

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

    - name: Final check
      shell: sleep 2 && curl -s http://127.0.0.1:8081/ | head -2
      register: check

    - debug:
        msg: "Apps running. Check localhost:8081, :8082, :8083"
