Vagrant.configure(2) do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "server" do |server|
    server.vm.hostname = "server.loc.ras"
    server.vm.network "private_network", ip: "192.168.56.14"
  end

#  config.vm.provision  "ansible" do |ansible|
#    ansible.playbook = "playbook/provision.yml"
#  end
end
