Hourly Web Server Report
=======================
Time Range: From 09/Aug/2025:18:45:43 to 09/Aug/2025:18:48:28

Top IP Addresses:
45       93.158.167.130
39       109.236.252.130
37       212.57.117.19
33       188.43.241.106
31       87.250.233.68
24       62.75.198.172
22       148.251.223.21
20       185.6.8.9
17       217.118.66.161
16       95.165.18.146

Top Requested URLs:
157      /
120      /wp-login.php
57       /xmlrpc.php
26       /robots.txt
12       /favicon.ico
11       400
9        /wp-includes/js/wp-embed.min.js?ver=5.0.4
7        /wp-admin/admin-post.php?page=301bulkoptions
7        /1
6        /wp-content/uploads/2016/10/robo5.jpg

HTTP Status Codes:
498      200
95       301
51       404
11       "-"
7        400
3        500
2        499
1        405
1        403
1        304

Server/Application Errors since last run:
    87.250.233.68 - - [14/Aug/2019:14:52:27 +0300] "GET / HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots yabs01)"rt=0.000 uct="-" uht="-" urt="-"
    141.8.141.136 - - [14/Aug/2019:15:52:52 +0300] "GET / HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots yabs01)"rt=0.000 uct="-" uht="-" urt="-"
    93.158.167.130 - - [14/Aug/2019:16:18:16 +0300] "GET / HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots yabs01)"rt=0.000 uct="-" uht="-" urt="-"
    5.45.203.12 - - [14/Aug/2019:16:53:55 +0300] "GET / HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots yabs01)"rt=0.000 uct="-" uht="-" urt="-"
    87.250.233.76 - - [14/Aug/2019:17:52:20 +0300] "GET / HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots yabs01)"rt=0.000 uct="-" uht="-" urt="-"
    93.158.167.130 - - [14/Aug/2019:17:55:02 +0300] "GET / HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots yabs01)"rt=0.000 uct="-" uht="-" urt="-"
    87.250.233.68 - - [14/Aug/2019:19:02:51 +0300] "GET / HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots yabs01)"rt=0.000 uct="-" uht="-" urt="-"
    93.158.167.130 - - [14/Aug/2019:19:16:50 +0300] "GET / HTTP/1.1" 404 169 "-" "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots yabs01)"rt=0.000 uct="-" uht="-" urt="-"
    185.142.236.35 - - [14/Aug/2019:19:23:18 +0300] "GET /.well-known/security.txt HTTP/1.1" 404 169 "-" "-"rt=0.000 uct="-" uht="-" urt="-"
